### ISSUE TITLE
How to find [xxteaKey] [sign] in apk file

### ISSUE THREAD

**Issue by takaaptech** [shiyingqi/luac-Decryption#1]
Hi!
From the command line, I see we need [xxteaKey] [sign] for Decryption.
In extracted apk file how can we find that information?
Thank you so much!

**Comment by Mas0nShi** [comment]
First of all, it needs to be explained that luac-Decryption is only applicable to` .lua` that uses xxtea encryption, and there is no way for the bytecode compiled by luajit.
How to find key and sign:
1. Use notepad to open any luac file. If you find that the beginning is obviously plaintext, then that section of plaintext is sign, otherwise this may not be the use of xxtea.
2. You need to find `libcocos2dlua.so` in the `lib` directory and use IDA to disassemble. Here are two common ways to find the key.

> 1. The sign obtained by IDA Shift+F12 search may contain the key near the sign.
> 2. Frida native hook, hook the export method of `setXXTEAKeyAndSign` (if any)

Write an example here:

```javascript
function coco2dx_lua_hook(){
    Java.perform(function(){
        var ptr = Module.findExportByName("libcocos2dlua.so", "_ZN7cocos2d8LuaStack18setXXTEAKeyAndSignEPKciS2_i");
        if(ptr==null){return 0;}
        console.log("Find the method.");
        Interceptor.attach(ptr, {
            onEnter:function(arg){
                console.log("Hooking.");
                console.log("[Key] - " + Memory.readCString(arg[1]));
                console.log("[Sign] - " + Memory.readCString(arg[3]));
            },
            onLeave:function(arg){
                console.log("Hooking exit.");
            }
        })
    })
}
setImmediate(function() {
    setTimeout(coco2dx_lua_hook, 10);
    });
```

**Comment by takaaptech** [comment]
@shiyingqi Thank you so much!

**Comment by Al-Mostapha** [comment]
Hi I tried to install frida to get key and sign but there is some problem in frida 
can i give you file and get key and sign

**Comment by Al-Mostapha** [comment]
https://ufile.io/iqt4i16m
Link for object

**Comment by Mas0nShi** [comment]
> https://ufile.io/iqt4i16m Link for object

seems not xxtea. you can take a look at `AppDelegate::startLoadLua`.

**Comment by Al-Mostapha** [comment]
but all function for xxtea is found and engine stack is seting key and sign 
here  is 2 files lua 
https://ufile.io/70amt3o0

can you try to get key and sign ?
i tried to get key code from ghibra but i failed

**Comment by Mas0nShi** [comment]
> but all function for xxtea is found and engine stack is seting key and sign here is 2 files lua https://ufile.io/70amt3o0

file header: 1B 4C 75 61 51 (LUAQ)
lua5.1, you can decompile by unluac.

https://imgur.com/a/MZJLiY2

**Comment by Al-Mostapha** [comment]
Thank You Very much!
it worked well
